# Generated by Django 4.1.3 on 2022-11-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('mobile', models.CharField(default='+91', max_length=15, unique=True)),
                ('email', models.EmailField(default='@gmail.com', max_length=100, unique=True)),
                ('pincode', models.IntegerField()),
                ('token', models.CharField(max_length=100)),
                ('mobile_otp', models.CharField(max_length=100)),
                ('email_otp', models.CharField(max_length=100)),
                ('blank1', models.CharField(max_length=100)),
                ('blank2', models.CharField(max_length=100)),
                ('blank3', models.CharField(max_length=100)),
                ('blank4', models.BooleanField(default=False)),
                ('blank5', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
